name: lists_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  uuid: ^3.0.6
  shared_preferences: ^2.0.13
  provider: ^6.0.2
  intl: ^0.17.0
  beamer: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_name: ^0.0.1
  flutter_native_splash: ^1.3.3 # app load screen
  flutter_launcher_icons: ^0.9.2 # app menu icon changer

dependency_overrides:
  yaml: ^3.1.0

flutter:
  uses-material-design: true
# flutter_native_splash:
#   color: "#ffffff"
#   image: lib/assets/imgs/icon.png
#   color_dark: "#1a1a1a"
#   image_dark: lib/assets/imgs/icon.png
#   android: true
#   ios: true
#   # android_gravity: fill
#   # ios_content_mode: scaleAspectFill

#   # flutter pub run flutter_native_splash:create

# flutter_icons:
#   android: true
#   ios: true
#   image_path: lib/assets/imgs/icon.png

#   # flutter pub run flutter_launcher_icons:main

# flutter_launcher_name:
#   name: "Lists app"

#   # flutter pub run flutter_launcher_name:main
